### ISSUE TITLE
Use fakeroot for building

### ISSUE THREAD

**Issue by AladW** [simonclausen/dnscrypt-autoinstall#64]
The `sudo bash` cludgery was introduced because of #10, as running gpg as sudo would break the permissions on the user gpg folder. A better solution would be to fully separate unprivileged sections by building with fakeroot, leaving root to move over (e.g wtith rsync) files to system locations and run ldconfig on fedora. This has the added benefit that users have a compiled tarball at their disposal, and don't run sudo make install.

http://www.linuxfromscratch.org/hints/downloads/files/fakeroot.txt
## Done
- [X] Exit on errors (#24)
- [X] Build and download as dedicated user
- [X] Remove sudo dependency (#69)
- [X] Create packages with fakeroot
- [X] Configure resolver with resolvers.csv (#62)
- [X] systemd service (#43)
- [x] sysvinit service (CentOS 6, Debian 7)
- [X] Remove installed files
- [X] Check for running DNS server
- [X] Retrieve newest libsodium version (#82)
- [X] Use absolute path for resolv.conf (#79)
- [X] Restore resolv.conf backup
- [X] Configure resolver after installation
- [X] Add MIT license (#86)
- [X] Additional download checks (#70)
- [X] Option for unencrypted DNS (#35)
- [X] Remove systemd configuration on uninstall
## Todo
- [ ] Verify resolvers.csv signature
- [ ] Start services depending on distribution / sysvinit support
- [ ] Detect libsodium version / query deletion (#56)
- [ ] Run backup resolver
- [x] Use different service name? (`dnscrypt-autoinstall.service`)
- [x] Improve file removal routine

**Comment by AladW** [comment]
This is what I have in mind so far:

1. A script to fetch and verify dnscrypt/libsodium tarballs, build them, and install the files to an archives via fakeroot/bsdtar. See: https://gist.github.com/Earnestly/bebad057f40a662b5cc3
2. A wrapper to install the needed dependencies, depending on distro detected (```/etc/debian_version``` e.a) and configure services

**Comment by AladW** [comment]
Working prototype for 1.: https://gist.github.com/AladW/273dd7b8f6d5a71409531aaf5bc41463

**Comment by AladW** [comment]
I've started a rewrite in the `fakeroot` branch; please add any thoughts as things progress.

**Comment by simonclausen** [comment]
Great!

**Comment by AladW** [comment]
The script should now be fully functional in Debian 8 and Ubuntu 16.04.

**Comment by AladW** [comment]
Sorry, I got busy with other projects. Will try to finish this as soon as possible.

**Comment by simonclausen** [comment]
Archiving repo, see last comment in #108
